-- Reference source for the PartyWidgetFix LPB overlay.
-- The live bytecode patch is generated by:
-- tools/actions/build_party_widget_fix_overlay.py

function PartyRootWidget.processUICommandCancel(self, ...)
  return desktopWidget:closeWidgetDirect(self)
end

-- In PartyRootWidget.processUICommandOperate, the existing Find branch becomes:
--
-- if command == "Button_PcMatching_Find" then
--   if self.work.party < 3 then
--     return
--   end
--   desktopWidget:openChildWidget("PcSearchWidget", self, true)
--   return
-- end
